config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get '/about', to: 'pages#about', as: 'about'
  
  get '/bba', to: 'pages#bba', as: 'bba'
  get '/bcom', to: 'pages#bcom', as: 'bcom'
  get '/pu', to: 'pages#pu', as: 'pu'

  get '/contact-us', to: 'contacts#new', as: '/contact-us'
  post '/thanks' => "contacts#create", as: :thanks 
  get '/thanks', to: 'contacts#thanks'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :telephone, :validate => /\A(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\z/
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :type,      :validate => true
  attribute :nickname,  :captcha  => true

  def headers
    {
      :subject => "Contact Form",
      :to => "svani4193@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request

    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message. Please try again after sometime!'
      render :new
    end
  end

  def thanks
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def bba
  end

  def bcom
  end

  def pu
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/create.html.erb
<h1 align= "center"> Hey there! </h1>
<hr />
<div class="row">
  <div class="col-md-12">
    <div class="thanks center">
      <h1 align="center">Thank you for filling out your information :)</h1>
      <p align="center">We have received your message and we try to respond as soon as possible. If your enquiry is urgent, please feel free to contact us at the telephone number listed below: </p> <br/>
                <p><i class="fa fa-phone"></i> 
                    <abbr title="Phone" class="glyphicon glyphicon-phone">P</abbr>: (+91) 8088886797 </p>
                <p> Or drop us an email <i class="fa fa-envelope-o"></i> 
                    <abbr title="Email" class="glyphicon glyphicon-envelope">E</abbr>: <a href="mailto:svani4193@gmail.com">svani4193@gmail.com</a>
                </p>
                <br/>
                <p><%= link_to "Back to homepage", root_path, class: "col-md-4 col-md-offset-4 btn-lg btn-xlarge" %></p>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<h1 align="center"> Enquiry / Contact </h1>
<hr />

<% if @contact.errors.any? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(@contact.errors.count, 'error') %>
            prohibited this <%= @contact.class %> from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% @contact.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>


<div class="row">
  <div class="col-md-12">

    <%= form_for(@contact, :url => thanks_path,:html => {class: "form-horizontal", role: "form"}) do |f| %>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Please enter in your name", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :telephone %>
        </div>
        <div class="col-md-8">
          <%= f.telephone_field :telephone, class: "form-control", placeholder: "Please enter in your phone number" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :type, 'Type of Course' %>
        </div>
        <div class="col-md-8">
          
          <%= f.radio_button :type, 'Regular Course', :checked => true %> 
          <%= f.label :type, 'Regular Course', :value => 'Regular Course' %>
          <%= f.radio_button :type, 'Crash Course' %>
          <%= f.label :type, 'Crash Course', :value => 'Crash Course' %>
          

        </div>
      </div>


      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :email %>
        </div>
        <div class="col-md-8">
          <%= f.email_field :email, rows: 10, class: "form-control", placeholder: "Please enter in your email where we can contact" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :message %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :message, as: :text, rows: 10, class: "form-control", placeholder: "Please describe your query" %>
        </div>
      </div>

      <div class="hidden">
        <%= f.label :nickname %><br>
        <%= f.text_field :nickname, hint: 'leave this field blank' %>
      </div>



      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit 'Submit Query!', class: "btn btn-primary btn-lg btn-xlarge" %>
        </div>
        <div class="col-md-4 col-md-offset-6 colormatch"> [<%= link_to 'Cancel and go back to home page', root_path %>] </div>
      </div>

    <% end %>

    
  </div>
</div>

<!-- Content Row -->
        <div class="row">
            <!-- Map Column -->
            <div class="col-md-8">
                <!-- Embedded Google Map -->
                <iframe src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d15555.611450859196!2d77.5447342!3d12.9139644!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sin!4v1497986284917" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
            <!-- Contact Details Column -->
            <div class="col-md-4">
                <h3>Contact Details</h3>
                <p>
                    No 137 SPURTHI RESIDENCY<br>3RD MAIN 4TH CROSS CHIKKALASANDRA<br>
                    RAMANJANEYANAGAR<br>BANGALORE 560061<br/>
                </p>
                <p><i class="fa fa-phone"></i> 
                    <abbr title="Phone" class="glyphicon glyphicon-phone">P</abbr>: (+91) 8088886797 </p>
                <p><i class="fa fa-envelope-o"></i> 
                    <abbr title="Email" class="glyphicon glyphicon-envelope">E</abbr>: <a href="mailto:svani4193@gmail.com">svani4193@gmail.com</a>
                </p>
                <p><i class="fa fa-clock-o"></i> 
                    <abbr title="Hours" class="glyphicon glyphicon-hourglass">H</abbr>: Monday - Sunday: 9:00 AM to 9:00 PM</p>
                <ul class="list-unstyled list-inline list-social-icons">
                    <li>
                        <a href="#"><i class="fa fa-facebook-square fa-2x"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-linkedin-square fa-2x"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-twitter-square fa-2x"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-google-plus-square fa-2x"></i></a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- /.row -->

app/views/layouts/_footer.html.erb
<hr>
<footer>
  <div class="container">
    <p>&copy; Vani Sindhnoor &#64; VANI TUTORIALS</p>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<div class="container-fluid">
    <!-- Second navbar for categories -->
    <nav class="navbar navbar-default">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
          <%= link_to "Vani Tutorials", root_path, class: "navbar-brand" %>
        </div>
    
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li> <%= link_to "Home", root_path %> </li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_us_path %></li>
            <li>
              <a class="btn btn-default btn-outline btn-circle"  data-toggle="collapse" href="#nav-collapse1" aria-expanded="false" aria-controls="nav-collapse1">Courses</a>
            </li>
          </ul>
          <ul class="collapse nav navbar-nav nav-collapse" id="nav-collapse1">
            <!-- <li><a href="#">More...</a></li> -->
            <!-- <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">More Subjects <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><%#= link_to "Management Process and Organisation Behaviour", mba_path %>
                            </li>
                            <li><%#= link_to "Strategic Management", mba_path %>
                            </li>
                            <li><%#= link_to "Business Research Methodology", mba_path %>
                            </li>
                            <li><%#= link_to "International Business", mba_path %>
                            </li>
                            <li><%#= link_to "Mercantile Law", bcom_path %>
                            </li>
                            <li><%#= link_to "Indian Constitution", bcom_path %>
                            </li>
                            <li><%#= link_to "Investment Management", mba_path %>
                            </li>
                            <li><%#= link_to "Financial Services", bcom_path %>
                            </li>
                            <li><%#= link_to "Human Resource Management", mba_path %>
                            </li>
                            <li><%#= link_to "Training and Development", mba_path %>
                            </li>
                        </ul>
              </li> -->
            
            <li><%= link_to "PU Commerce", pu_path %></li>
            <li><%= link_to "B.Com", bcom_path %></li>
            <li><%= link_to "BBA/BBM", bba_path %></li>
            
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav><!-- /.navbar -->
    
    
</div><!-- /.container-fluid -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VANI TUTORIALS</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/_display_subjects.html.erb
    <div class="panel-group" id="accordion">
      <% @subjects.each do |subject| %>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <%= subject.capitalize %>
                </h4> 
            </div>
        </div>
      <% end %>
    </div>
  
<!-- Template taken from https://blackrockdigital.github.io/startbootstrap-modern-business/faq.html -->

app/views/pages/about.html.erb
<!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">About
                    <small>VANI&nbsp;TUTORIALS</small>
                    <p class="glyphicon glyphicon-blackboard""></p>
                </h1>
                <!-- <ol class="breadcrumb">
                    <li><a href="index.html">Home</a>
                    </li>
                    <li class="active">About</li>
                </ol> -->
            </div>
        </div>
        <!-- /.row -->
        <div class="col-md-6">
            <blockquote>
                <p><b>
                The mediocre teacher tells.  &#09; The good teacher explains.  &#09; The superior teacher demonstrates.  &#09;The great teacher inspires.</b></p>
                <footer>William Arthur Ward</footer>
            </blockquote>
        </div>

        <div class="col-md-6">
            <p>At Vani Tutorials, we believe in and care about inspiring students with questions and  brainstorming sessions. We encourage them to focus on their strengths and help them to learn from their mistakes. Last but not the least, honor them with 1 on 1 times by providing feedback :) <br>
            Finally, we make sure to convince our students that his/her challenges of learning are worthwhile.</p>
            <p>We at Vani Tutorials, modify and customize lessons to specifically target each individual student. We find and establish relevant links between the course content and student's individual experiences and understanding in the real world.</p>
            <p> Some of the other salient feature include:
                <li> Complete coverage of Syllabus. </li>
                <li> Personal attention <b><i> Max 15 students in a batch. </i></b></li>
                <li> Clarity of concepts instead of mere dictation. </li>
                <li> Comprehensive Mock Tests. </li>
                <li> Special attention for weak students. </li>
                <li> Specially designed <b>Crash Course</b> (For students seeking admission for Crash Course)</li>
            </p>
        </div>

               
                
                
        
    </div>

app/views/pages/bba.html.erb
<h1 class="page-header">
    BBA/BBM <small class="ttl">subjects</small>
</h1>
<div class="row">
  <div class="col-lg-12">
    <% @subjects = ['Management Process and Organisation Behaviour', 'Strategic Management', 'Business Research Methodology', 'International Business', 'Investment Management', 'Human Resource Management', 'Training and Development', 'Operational Research', 'Fundamentals of Accounting', 'Financial Management', 'Compensation Management'] %>
    <%= render 'display_subjects', collection: @subjects %>
  </div>
</div>

<%#= render 'shared/page_title', title: "Create a new recipe" %>

app/views/pages/bcom.html.erb
<h1 class="page-header">
    B.Com <small class="ttl">subjects</small>
</h1>
<div class="row">
  <div class="col-lg-12">
    <% @subjects = ['Mercantile Law', 'Indian Constitution', 'Financial Services', 'Fundamentals of Accounting', 'Corporate Accounting', 'Taxation', 'Cost Accounting', 'Auditing'] %>
    <%= render 'display_subjects', collection: @subjects %>
  </div>
</div>

<%#= render 'shared/page_title', title: "Create a new recipe" %>

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h1>Welcome to Vani Tutorials</h1>
  <h2>The best place to learn and excel!</h2>
  <!--<p><%# = link_to "Sign up or log in", "#", class: "btn btn-primary btn-lg btn-xlarge" %></p>-->
</div>

<div class="row">
  <div class="col-md-4">
    <h2>BBA/BBM</h2>
    <p>The BBM degree is designed to teach students the skills necessary to perform leadership roles in the business and corporate world. </p> 
    <p>Coaching at Vani Tutorials involves training through practical experience in the form of case studies, projects, presentations apart from the regular coaching.</p>
    <p>Join us and deep dive in the world of management studies.</p>
    
    <p><%= link_to "View Subjects", bba_path, class: "btn btn-primary" %></p>
  </div>
  <div class="col-md-4">
    <h2>B.Com</h2>
    <p>A Bachelor of Commerce or B.Com is specially designed to provide students, managerial skills in commerce associated disciplines such as accounting, finance, marketing and advertising amongst others.</p>
    <p>Here at Vani Tutorials we offer excellent coaching for B.Com by implementing best teaching strategies which will make students comfortable with the subjects and easy to grasp the concepts.</p>
    
    <p><%= link_to "View Subjects", bcom_path, class: "btn btn-primary" %></p>
 </div>
  <div class="col-md-4">
    <h2>PU Commerce</h2>
    <!-- <p><blockquote>Without a solid foundation, you will have trouble creating anything of value.</blockquote></p> -->
    <p>PUC plays a major significant role in laying strong foundation of basic concepts of your professional career. Scoring well and understanding the basics thoroughly will boost your confidence going ahead.</p>
    <p>Here at Vani Tutorials we provide personalized mentoring to the PU Commerce students which includes regular class test, special classes for weak students, individual attention along with extensive preparation for final examination.</p>
    
    <p><%= link_to "View Subjects", pu_path, class: "btn btn-primary" %></p>
  </div>
</div>

app/views/pages/pu.html.erb
<h1 class="page-header">
    PU <small class="ttl">subjects</small>
</h1>
<div class="row">
  <div class="col-lg-12">
    <% @subjects = ['Accounts', 'Business Studies', 'Statistics', 'Economics'] %>
    <%= render 'display_subjects', collection: @subjects %>
  </div>
</div>

<%#= render 'shared/page_title', title: "Create a new recipe" %>